spring.application.name=rewind-back-end

#JPA configurations
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=create

# Postgrees configurations
spring.datasource.url=jdbc:postgresql://localhost:5432/Rewind-test?currentSchema=public
spring.datasource.username=postgres
spring.datasource.password=87654321

server.servlet.context-path=/api/v1

server.port=8081
