spring.application.name=rewind-back-end

#JPA configurations
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=create

#Postgrees configurations
#MySQL Database Connection properties
spring.datasource.url=jdbc:mysql://localhost:3306/rewind-test?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=12345678


server.servlet.context-path=/api/v1

server.port=8081
